[versions]
android-gradle-plugin = "8.10.0"
android-compileSdk = "35"
android-minSdk = "24"
androidx-test-espresso = "3.5.1"
androidx-test-junit = "1.2.1"
androidx-test-rules = "1.6.1"
androidx-test-runner = "1.6.2"
bignum = "0.3.10"
kotlin = "2.1.21"
kotlin-poet = "2.0.0"
kotlinx-datetime = "0.7.1"
kotlinx-serialization-json = "1.8.1"
maven-publish = "0.29.0"
spotless = "7.0.1"

[libraries]
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "bignum"}
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-poet" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }


[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }